// <auto-generated />
using GamebookCihullick.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamebookCihullick.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241215221117_ListConnections")]
    partial class ListConnections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GamebookCihullick.Server.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GamebookCihullick.Server.Models.LocationConnection", b =>
                {
                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedLocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationID", "ConnectedLocationID");

                    b.HasIndex("ConnectedLocationID");

                    b.ToTable("LocationConnections");
                });

            modelBuilder.Entity("GamebookCihullick.Server.Models.LocationConnection", b =>
                {
                    b.HasOne("GamebookCihullick.Server.Models.Location", "ConnectedLocation")
                        .WithMany()
                        .HasForeignKey("ConnectedLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamebookCihullick.Server.Models.Location", "Location")
                        .WithMany("Connections")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConnectedLocation");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GamebookCihullick.Server.Models.Location", b =>
                {
                    b.Navigation("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
